server:
  port: "8000"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "shance_db"

jwt:
  secret: "your-secret-key"
  access_token_ttl: "15m"
  refresh_token_ttl: "720h" # 30 days 