basePath: /api/v1
definitions:
  domain.Tag:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  domain.User:
    properties:
      city:
        type: string
      country:
        type: string
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      phone:
        type: string
      role:
        type: string
      tags:
        items:
          $ref: '#/definitions/domain.Tag'
        type: array
    type: object
  handler.CreateProjectRequest:
    properties:
      description:
        example: Описание проекта
        type: string
      name:
        example: Новый проект
        type: string
      photo:
        example:
        - '[''photo1.jpg'''
        - ' ''photo2.jpg'']'
        items:
          type: string
        type: array
      subtitle:
        example: Подзаголовок проекта
        type: string
      tags:
        example:
        - '[''tag1'''
        - ' ''tag2'']'
        items:
          type: string
        type: array
      title:
        example: Заголовок проекта
        type: string
    required:
    - name
    type: object
  handler.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  handler.LoginRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password123
        type: string
    required:
    - email
    - password
    type: object
  handler.ProjectResponse:
    properties:
      created_at:
        example: "2024-03-20T12:00:00Z"
        type: string
      description:
        example: Описание проекта
        type: string
      id:
        example: 1
        type: integer
      name:
        example: Новый проект
        type: string
      photo:
        example:
        - '[''photo1.jpg'''
        - ' ''photo2.jpg'']'
        items:
          type: string
        type: array
      subtitle:
        example: Подзаголовок проекта
        type: string
      tags:
        example:
        - '[''tag1'''
        - ' ''tag2'']'
        items:
          type: string
        type: array
      title:
        example: Заголовок проекта
        type: string
      user:
        $ref: '#/definitions/handler.UserResponse'
      user_id:
        example: 1
        type: integer
    type: object
  handler.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  handler.RegisterRequest:
    properties:
      city:
        example: Moscow
        type: string
      country:
        example: Russia
        type: string
      email:
        example: user@example.com
        type: string
      first_name:
        example: John
        type: string
      last_name:
        example: Doe
        type: string
      password:
        example: password123
        minLength: 6
        type: string
      phone:
        example: "+79001234567"
        type: string
      role:
        example: user
        type: string
      tags:
        example:
        - '[''tag1'''
        - ' ''tag2'']'
        items:
          type: string
        type: array
    required:
    - email
    - first_name
    - last_name
    - password
    type: object
  handler.TokenResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  handler.UpdateProjectRequest:
    properties:
      description:
        example: Новое описание
        type: string
      name:
        example: Обновленный проект
        type: string
      photo:
        example:
        - '[''new_photo1.jpg'''
        - ' ''new_photo2.jpg'']'
        items:
          type: string
        type: array
      subtitle:
        example: Новый подзаголовок
        type: string
      tags:
        example:
        - '[''new_tag1'''
        - ' ''new_tag2'']'
        items:
          type: string
        type: array
      title:
        example: Новый заголовок
        type: string
    type: object
  handler.UpdateUserRequest:
    properties:
      city:
        example: Санкт-Петербург
        type: string
      description:
        example: Новая роль
        type: string
      name:
        example: Новое имя
        type: string
      photo:
        example:
        - new_photo1.jpg
        - ' new_photo2.jpg'
        items:
          type: string
        type: array
      subtitle:
        example: Новый номер телефона
        type: string
      tags:
        example: new_tag1, new_tag2
        type: string
      title:
        example: Новая фамилия
        type: string
    type: object
  handler.UserResponse:
    properties:
      email:
        example: ivan@example.com
        type: string
      first_name:
        example: Иван
        type: string
      id:
        example: 1
        type: integer
      last_name:
        example: Иванов
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: API для управления проектами
  title: Shance API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Аутентифицирует пользователя и возвращает refresh token
      parameters:
      - description: Данные для входа
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.TokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Вход в систему
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Обновляет пару токенов используя refresh token
      parameters:
      - description: Refresh token
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.TokenResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Обновление токенов
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Создает нового пользователя и возвращает refresh token
      parameters:
      - description: Данные для регистрации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.TokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Регистрация нового пользователя
      tags:
      - auth
  /projects:
    get:
      consumes:
      - application/json
      description: Возвращает список всех проектов
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.ProjectResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Получение всех проектов
      tags:
      - projects
    post:
      consumes:
      - application/json
      description: Создает новый проект в системе
      parameters:
      - description: Данные проекта
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.CreateProjectRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.ProjectResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Создание нового проекта
      tags:
      - projects
  /projects/{id}:
    delete:
      consumes:
      - application/json
      description: Удаляет проект по указанному ID
      parameters:
      - description: ID проекта
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Удаление проекта
      tags:
      - projects
    get:
      consumes:
      - application/json
      description: Возвращает проект по указанному ID
      parameters:
      - description: ID проекта
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ProjectResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Получение проекта по ID
      tags:
      - projects
    put:
      consumes:
      - application/json
      description: Обновляет данные существующего проекта
      parameters:
      - description: ID проекта
        in: path
        name: id
        required: true
        type: integer
      - description: Данные проекта
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.UpdateProjectRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ProjectResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Обновление проекта
      tags:
      - projects
  /projects/search:
    get:
      consumes:
      - application/json
      description: Возвращает список проектов, названия которых содержат поисковый
        запрос
      parameters:
      - description: Поисковый запрос
        in: query
        name: q
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.ProjectResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Поиск проектов по названию
      tags:
      - projects
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Возвращает данные пользователя по указанному ID
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Получение пользователя по ID
      tags:
      - users
  /users/me:
    get:
      consumes:
      - application/json
      description: Возвращает данные авторизованного пользователя
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Получение данных текущего пользователя
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Обновляет данные авторизованного пользователя
      parameters:
      - description: Данные пользователя
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Обновление данных текущего пользователя
      tags:
      - users
schemes:
- http
swagger: "2.0"
